package techoffice;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FlightResp implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String flightResCode;
   private java.lang.Double flightPrice;
   private java.lang.String flightResStatus;
   private java.lang.Integer flightDisc;
   private java.lang.String flightNo;
   private java.lang.String flightDate;
   private java.lang.String flightFrom;
   private java.lang.String flightTo;
   private java.lang.Integer flightPassengers;

   public FlightResp()
   {
   }

   public java.lang.String getFlightResCode()
   {
      return this.flightResCode;
   }

   public void setFlightResCode(java.lang.String flightResCode)
   {
      this.flightResCode = flightResCode;
   }

   public java.lang.Double getFlightPrice()
   {
      return this.flightPrice;
   }

   public void setFlightPrice(java.lang.Double flightPrice)
   {
      this.flightPrice = flightPrice;
   }

   public java.lang.String getFlightResStatus()
   {
      return this.flightResStatus;
   }

   public void setFlightResStatus(java.lang.String flightResStatus)
   {
      this.flightResStatus = flightResStatus;
   }

   public java.lang.Integer getFlightDisc()
   {
      return this.flightDisc;
   }

   public void setFlightDisc(java.lang.Integer flightDisc)
   {
      this.flightDisc = flightDisc;
   }

   public java.lang.String getFlightNo()
   {
      return this.flightNo;
   }

   public void setFlightNo(java.lang.String flightNo)
   {
      this.flightNo = flightNo;
   }

   public java.lang.String getFlightDate()
   {
      return this.flightDate;
   }

   public void setFlightDate(java.lang.String flightDate)
   {
      this.flightDate = flightDate;
   }

   public java.lang.String getFlightFrom()
   {
      return this.flightFrom;
   }

   public void setFlightFrom(java.lang.String flightFrom)
   {
      this.flightFrom = flightFrom;
   }

   public java.lang.String getFlightTo()
   {
      return this.flightTo;
   }

   public void setFlightTo(java.lang.String flightTo)
   {
      this.flightTo = flightTo;
   }

   public java.lang.Integer getFlightPassengers()
   {
      return this.flightPassengers;
   }

   public void setFlightPassengers(java.lang.Integer flightPassengers)
   {
      this.flightPassengers = flightPassengers;
   }

   public FlightResp(java.lang.String flightResCode,
         java.lang.Double flightPrice, java.lang.String flightResStatus,
         java.lang.Integer flightDisc, java.lang.String flightNo,
         java.lang.String flightDate, java.lang.String flightFrom,
         java.lang.String flightTo, java.lang.Integer flightPassengers)
   {
      this.flightResCode = flightResCode;
      this.flightPrice = flightPrice;
      this.flightResStatus = flightResStatus;
      this.flightDisc = flightDisc;
      this.flightNo = flightNo;
      this.flightDate = flightDate;
      this.flightFrom = flightFrom;
      this.flightTo = flightTo;
      this.flightPassengers = flightPassengers;
   }

}