package com.redhat;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CarReq implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String carRentalCo;

   private java.lang.String carType;

   private java.lang.String carCity;
   
   private java.lang.String carStartDate;
   
   private java.lang.Integer carDays;

   public CarReq()
   {
   }

   
   public java.lang.String getCarRentalCo()
   {
      return this.carRentalCo;
   }

   public void setCarRentalCo(java.lang.String carRentalCo)
   {
      this.carRentalCo = carRentalCo;
   }

   public java.lang.String getCarType()
   {
      return this.carType;
   }

   public void setCarType(java.lang.String carType)
   {
      this.carType = carType;
   }

   public java.lang.String getCarCity()
   {
      return this.carCity;
   }

   public void setCarCity(java.lang.String carCity)
   {
      this.carCity = carCity;
   }

 
   public CarReq( java.lang.String carRentalCo, java.lang.String carType,
         java.lang.String carCity)
   {
      this.carRentalCo = carRentalCo;
      this.carType = carType;
      this.carCity = carCity;
   }


public java.lang.String getCarStartDate() {
	return carStartDate;
}


public void setCarStartDate(java.lang.String carStartDate) {
	this.carStartDate = carStartDate;
}


public java.lang.Integer getCarDays() {
	return carDays;
}


public void setCarDays(java.lang.Integer carDays) {
	this.carDays = carDays;
}

}