package com.redhat;

import javax.xml.bind.annotation.XmlRootElement;



/**
 * This class was automatically generated by the data modeler tool.
 */
public class FlightReq implements java.io.Serializable
{

   static final long serialVersionUID = 1L;


   private java.lang.String flightNo;

   private java.lang.String flightDate;

   private java.lang.String flightFrom;

   private java.lang.String flightTo;

   private java.lang.Integer flightPassengers;

   public FlightReq()
   {
   }

   

   public java.lang.String getFlightNo()
   {
      return this.flightNo;
   }

   public void setFlightNo(java.lang.String flightNo)
   {
      this.flightNo = flightNo;
   }

   public java.lang.String getFlightDate()
   {
      return this.flightDate;
   }

   public void setFlightDate(java.lang.String flightDate)
   {
      this.flightDate = flightDate;
   }

   public java.lang.String getFlightFrom()
   {
      return this.flightFrom;
   }

   public void setFlightFrom(java.lang.String flightFrom)
   {
      this.flightFrom = flightFrom;
   }

   public java.lang.String getFlightTo()
   {
      return this.flightTo;
   }

   public void setFlightTo(java.lang.String flightTo)
   {
      this.flightTo = flightTo;
   }

   public java.lang.Integer getFlightPassengers()
   {
      return this.flightPassengers;
   }

   public void setFlightPassengers(java.lang.Integer flightPassengers)
   {
      this.flightPassengers = flightPassengers;
   }

   public FlightReq( java.lang.String flightNo, java.lang.String flightDate,
         java.lang.String flightFrom, java.lang.String flightTo,
         java.lang.Integer flightPassengers)
   {
      
      this.flightNo = flightNo;
      this.flightDate = flightDate;
      this.flightFrom = flightFrom;
      this.flightTo = flightTo;
      this.flightPassengers = flightPassengers;
   }

}