package techoffice;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class HotelResp implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String hotelResCode;
   private java.lang.Double hotelPrice;
   private java.lang.String hotelResStatus;
   private java.lang.Integer hotelDisc;
   private java.lang.String hotelArrivalDate;
   private java.lang.Integer hotelNights;
   private java.lang.String hotelCity;
   private java.lang.String hotelId;

   public HotelResp()
   {
   }

   public java.lang.String getHotelResCode()
   {
      return this.hotelResCode;
   }

   public void setHotelResCode(java.lang.String hotelResCode)
   {
      this.hotelResCode = hotelResCode;
   }

   public java.lang.Double getHotelPrice()
   {
      return this.hotelPrice;
   }

   public void setHotelPrice(java.lang.Double hotelPrice)
   {
      this.hotelPrice = hotelPrice;
   }

   public java.lang.String getHotelResStatus()
   {
      return this.hotelResStatus;
   }

   public void setHotelResStatus(java.lang.String hotelResStatus)
   {
      this.hotelResStatus = hotelResStatus;
   }

   public java.lang.Integer getHotelDisc()
   {
      return this.hotelDisc;
   }

   public void setHotelDisc(java.lang.Integer hotelDisc)
   {
      this.hotelDisc = hotelDisc;
   }

   public java.lang.String getHotelArrivalDate()
   {
      return this.hotelArrivalDate;
   }

   public void setHotelArrivalDate(java.lang.String hotelArrivalDate)
   {
      this.hotelArrivalDate = hotelArrivalDate;
   }

   public java.lang.Integer getHotelNights()
   {
      return this.hotelNights;
   }

   public void setHotelNights(java.lang.Integer hotelNights)
   {
      this.hotelNights = hotelNights;
   }

   public java.lang.String getHotelCity()
   {
      return this.hotelCity;
   }

   public void setHotelCity(java.lang.String hotelCity)
   {
      this.hotelCity = hotelCity;
   }

   public java.lang.String getHotelId()
   {
      return this.hotelId;
   }

   public void setHotelId(java.lang.String hotelId)
   {
      this.hotelId = hotelId;
   }

   public HotelResp(java.lang.String hotelResCode,
         java.lang.Double hotelPrice, java.lang.String hotelResStatus,
         java.lang.Integer hotelDisc, java.lang.String hotelArrivalDate,
         java.lang.Integer hotelNights, java.lang.String hotelCity,
         java.lang.String hotelId)
   {
      this.hotelResCode = hotelResCode;
      this.hotelPrice = hotelPrice;
      this.hotelResStatus = hotelResStatus;
      this.hotelDisc = hotelDisc;
      this.hotelArrivalDate = hotelArrivalDate;
      this.hotelNights = hotelNights;
      this.hotelCity = hotelCity;
      this.hotelId = hotelId;
   }

}