package com.redhat;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class HotelReq implements java.io.Serializable
{

   static final long serialVersionUID = 1L;


   private java.lang.String hotelArrivalDate;

   private java.lang.Integer hotelNights;

   private java.lang.String hotelCity;

   private java.lang.String hotelId;

   public HotelReq()
   {
   }

   
   public java.lang.String getHotelArrivalDate()
   {
      return this.hotelArrivalDate;
   }

   public void setHotelArrivalDate(java.lang.String hotelArrivalDate)
   {
      this.hotelArrivalDate = hotelArrivalDate;
   }

   public java.lang.Integer getHotelNights()
   {
      return this.hotelNights;
   }

   public void setHotelNights(java.lang.Integer hotelNights)
   {
      this.hotelNights = hotelNights;
   }

   public java.lang.String getHotelCity()
   {
      return this.hotelCity;
   }

   public void setHotelCity(java.lang.String hotelCity)
   {
      this.hotelCity = hotelCity;
   }

   public java.lang.String getHotelId()
   {
      return this.hotelId;
   }

   public void setHotelId(java.lang.String hotelId)
   {
      this.hotelId = hotelId;
   }

   public HotelReq(java.lang.String hotelArrivalDate, java.lang.Integer hotelNights,
         java.lang.String hotelCity, java.lang.String hotelId)
   {
      this.hotelArrivalDate = hotelArrivalDate;
      this.hotelNights = hotelNights;
      this.hotelCity = hotelCity;
      this.hotelId = hotelId;
   }

}